Feature/opt in mode
looorent/keycloak-api-rails pull request #48
Opened 2023-04-12 15:20 UTC by theSteveMitchell

Follow-up to https://github.com/looorent/keycloak-api-rails/pull/47. This handles a minor edge case that will frequently happen when testing in a Rails app.

When using opt-in mode, Keycloak-api-rails (KAR) is now going to be called directly from controllers, including when controllers are called from tests (rspec, minitest, etc.) Generally these tests won't include the full rails request context. Specifically, in rspec controller specs, REQUEST_URI will be nil. This was throwing an error on URI.parse While we could modify the application to only authenticate in non-test runs, I think it makes sense for KAR to handle a nil URI

We didn't have to worry about this in middleware mode, because rspec simply doesn't include the middleware in tests.

2023-04-12 22:27 UTC, looorent requested changes
Thanks for your contribution, @theSteveMitchell !
Could you take a look at these comments?

2023-04-12 22:27 UTC, looorent commented on lib/keycloak-api-rails/authentication.rb
> +      render status: :unauthorized, json: { error: "Invalid Token" }
I am not sure to understand this change. 
The previous behavior changed: the error message is not exposed in the json payload anymore.

2023-04-12 22:27 UTC, looorent commented on lib/keycloak-api-rails/helper.rb
> +      return "" unless uri.present?
The rest of the code does not "break" methods with `return`. To make it consistent, could you replace this instruction with something like:
```ruby
if uri.present?
 ...
else
  ""
end
```

2023-04-14 13:30 UTC, theSteveMitchell commented on lib/keycloak-api-rails/authentication.rb
> +      render status: :unauthorized, json: { error: "Invalid Token" }
Okay, updated.

2023-04-14 13:30 UTC, theSteveMitchell commented
@looorent thanks for feedback, made the requested changes

2023-04-15 09:43 UTC, looorent approved these changes

2023-04-15 09:44 UTC, merged

2023-04-15 09:46 UTC, looorent commented
Thanks for your contribution!
It is now available as `0.12.1`